### ISSUE TITLE
use deb.sury.org instead of dotdeb

### ISSUE THREAD

**Issue by snarky** [jebovic/ansible-php#1]
You can use http://deb.sury.org for PHP 5.6, 7.0, and 7.1 for Debian Jessie and PHP 7.0 and 7.1 for Debian Stretch.

@see https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/

**Comment by jebovic** [comment]
Nice catch @snarky !
It will be integrated in default role vars. As a workaround one can override defaults vars with group_vars or host_vars :

```yaml

#group_vars/all/_vars.yml
php_use_custom_repository: yes
php_custom_repositories_key_url: https://packages.sury.org/php/apt.gpg
php_custom_repositories:
  - deb https://packages.sury.org/php/ jessie main
```
